apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: extracto-fetch-api
  namespace: extracto
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: extracto-api.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: extracto-fetch-api
            port:
              number: 3000
