apiVersion: v1
kind: Service
metadata:
  name: extracto-fetch-api
  namespace: extracto
  labels:
    app: extracto-fetch-api
spec:
  type: ClusterIP
  selector:
    app: extracto-fetch-api
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
